data_download:
  days: 1095
  interval: '15'
  original_symbols:
  - 1000PEPEUSDT
  - 1INCHUSDT
  - AAVEUSDT
  - ADAUSDT
  - ALGOUSDT
  - APEUSDT
  - APTUSDT
  - ARBUSDT
  - ATOMUSDT
  - AVAXUSDT
  - AXSUSDT
  - BNBUSDT
  - BTCUSDT
  - CAKEUSDT
  - DOGEUSDT
  - DOTUSDT
  - DYDXUSDT
  - ENAUSDT
  - ENSUSDT
  - ETHUSDT
  - FARTCOINUSDT
  - GALAUSDT
  - GMTUSDT
  - GRIFFAINUSDT
  - HBARUSDT
  - ICPUSDT
  - JTOUSDT
  - LDOUSDT
  - LINKUSDT
  - LTCUSDT
  - MELANIAUSDT
  - NEARUSDT
  - OMUSDT
  - ONDOUSDT
  - OPUSDT
  - PNUTUSDT
  - POPCATUSDT
  - SOLUSDT
  - SUIUSDT
  - TAOUSDT
  - TESTUSDT
  - TIAUSDT
  - TONUSDT
  - TRBUSDT
  - TRUMPUSDT
  - TRXUSDT
  - TWTUSDT
  - UNIUSDT
  - WIFUSDT
  - XRPUSDT
  - ZEREBROUSDT
  symbols:
  - 1INCHUSDT
  - AAVEUSDT
  - ADAUSDT
  - ALGOUSDT
  - APEUSDT
  - APTUSDT
  - ARBUSDT
  - ATOMUSDT
  - AVAXUSDT
  - AXSUSDT
  - BNBUSDT
  - BTCUSDT
  - CAKEUSDT
  - DOGEUSDT
  - DOTUSDT
  - DYDXUSDT
  - ENAUSDT
  - ENSUSDT
  - ETHUSDT
  - GALAUSDT
  - GMTUSDT
  - HBARUSDT
  - ICPUSDT
  - JTOUSDT
  - LDOUSDT
  - LINKUSDT
  - LTCUSDT
  - NEARUSDT
  - OMUSDT
  - ONDOUSDT
  - OPUSDT
  - PNUTUSDT
  - POPCATUSDT
  - SOLUSDT
  - SUIUSDT
  - TIAUSDT
  - TONUSDT
  - TRUMPUSDT
  - TRXUSDT
  - TWTUSDT
  - UNIUSDT
  - WIFUSDT
  - XRPUSDT
  - ZEREBROUSDT
  unsupported_symbols:
  - 1000PEPEUSDT
  - FARTCOINUSDT
  - GRIFFAINUSDT
  - MELANIAUSDT
  - TAOUSDT
  - TESTUSDT
  - TRBUSDT
database:
  database: crypto_trading
  host: localhost
  password: null
  port: 5555
  user: ruslan
model:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  prediction_horizon: 100
  sequence_length: 60
paths:
  logs: logs/
  models: trained_model/
  plots: plots/
risk_profile:
  default_balance: 500
  leverage: 10
  risk_per_trade: 0.02
  stop_loss_pct_buy: 0.989
  stop_loss_pct_sell: 1.011
  take_profit_pct_buy: 1.058
  take_profit_pct_sell: 0.942
