version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crypto_postgres
    environment:
      POSTGRES_USER: ruslan
      POSTGRES_PASSWORD: your_secure_password_here
      POSTGRES_DB: crypto_trading
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ruslan -d crypto_trading"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: crypto_trading_data