#!/bin/bash
# Скрипт для настройки SSH на порту 2222

echo "=== Настройка SSH для порта 2222 ==="
echo ""
echo "Для настройки SSH на порту 2222 выполните следующие шаги:"
echo ""
echo "1. Создайте файл конфигурации SSH (требуется sudo):"
echo "   sudo nano /etc/ssh/sshd_config.d/port2222.conf"
echo ""
echo "2. Добавьте в файл следующие строки:"
echo "   Port 22"
echo "   Port 2222"
echo ""
echo "3. Проверьте конфигурацию:"
echo "   sudo sshd -t"
echo ""
echo "4. Откройте порт 2222 в файрволе:"
echo "   sudo ufw allow 2222/tcp"
echo ""
echo "5. Перезапустите SSH службу:"
echo "   sudo systemctl restart ssh"
echo ""
echo "6. Проверьте, что SSH слушает на обоих портах:"
echo "   sudo ss -tlnp | grep ssh"
echo ""
echo "7. Проверьте подключение:"
echo "   ssh -p 2222 $USER@localhost"
echo ""
echo "=== Альтернативный метод (изменение основного конфига) ==="
echo ""
echo "1. Откройте основной конфиг:"
echo "   sudo nano /etc/ssh/sshd_config"
echo ""
echo "2. Найдите строку #Port 22 и добавьте после неё:"
echo "   Port 22"
echo "   Port 2222"
echo ""
echo "3. Сохраните и выполните шаги 3-7 из первого метода"